defaultNamespace: prometheus-metrics-generator
helm:
  releaseName: prometheus-metrics-generator
  chart: prometheus-metrics-generator
  version: 0.5.0+c5141df30ebcf4ee724140918b3bafb7836c109d
  repo: https://jenkins:jenkins4ever@charts.dev.kende.pl
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: prometheus-metrics-generator.dev.kende.pl
        paths:
        - path: /
      tls:
      - secretName: prometheus-metrics-generator.dev.kende.pl
        hosts:
        - prometheus-metrics-generator.dev.kende.pl
    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
